pruek_note/urls.py
from django.urls import path
from .views import NoteListView, NoteDetailView

app_name = "note"
urlpatterns = [
    path('', NoteListView.as_view(), name='index'),  # ใช้ ListView
    path('<int:pk>/', NoteDetailView.as_view(), name='detail'),  # ใช้ DetailView
]

pruek_note/models.py
from django.db import models

class Note(models.Model):
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=999)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

pruek_note/views.py
from django.views.generic import ListView, DetailView

from .models import Note

class NoteListView(ListView):
    model = Note
    template_name = 'note/index.html'  # ชื่อไฟล์ Template
    context_object_name = 'notes'     # ชื่อ Context ที่ส่งไป Template (default: 'object_list')

class NoteDetailView(DetailView):
    model = Note
    template_name = 'note/detail.html' 
    context_object_name = 'note'       

pruek_note/templates/note/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ note.title }}</title>
</head>
<body>
    <h1>{{ note.title }}</h1>
    <p>{{ note.content }}</p>
    <a href="{% url 'note:index' %}">Back to all notes</a>
</body>
</html>

pruek_note/templates/note/index.html
<!DOCTYPE html>

<html>

<head>

    <title>All Notes</title>

</head>

<body>

    <h1>All Notes</h1>

    <ul>

        {% for n in notes %}

            <li>

                <a href="{% url 'note:detail' n.id %}">{{ n.title }}</a>

            
            </li>

        {% endfor %}

    </ul>

</body>

</html>